apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-init
  labels:
    app: cockroachdb
spec:
  template:
    spec:
      containers:
      - name: cluster-init
        annotations:
          pod.beta.kubernetes.io/init-containers: '[
            {
              "name": "init-check-cluster-status",
              "image": "busybox",
              "command": ["sh", "-c", "until nslookup cockroachdb-public:26257; do echo waiting for dbcluster; sleep 2; done;"]
            }
          ]'
        image: cockroachdb/cockroach:v1.1.2
        imagePullPolicy: IfNotPresent
        command:
          - "/cockroach/cockroach"
          - "init"
          - "--insecure"
          - "--host=cockroachdb-0.cockroachdb"
      restartPolicy: OnFailure
